### ISSUE TITLE
Additional code not available yet?

### ISSUE THREAD

**Issue by nicolasch96** [gfxdisp/asap#1]
Hello, 

in your paper and in the read me, you mention a GPU implementation and the implementation of several other algorithms. Is it possible to get access to those ?

Thank you !

**Comment by mikhailiuk** [comment]
Hi Nicolas,

Thank you for raising an issue!

The code will be available within the next few weeks. I will make sure to notify you once released.

Best,

Aliaksei

**Comment by mikhailiuk** [comment]
Hi @nicolasch96,

Thank you for raising an issue!

The code will be available within the next few weeks. I will make sure to notify you once released.

Best,

Aliaksei

**Comment by nicolasch96** [comment]
> Hi @nicolasch96,
> 
> Thank you for raising an issue!
> 
> The code will be available within the next few weeks. I will make sure to notify you once released.
> 
> Best,
> 
> Aliaksei

Thank you very much :)
