### ISSUE TITLE
Uniformity of the pair selection process

### ISSUE THREAD

**Issue by nicolasch96** [gfxdisp/asap#13]
Hello Aliaksei!

I have another problem with the pair selection process. After visualizing the comparison matrix of an experiment I had the following graph (what I did here is sorting the elements, then sum the upper and lower part of the matrix to get the total number of comparisons for a given pair (x1,x2) + (x2,x1) ): 

![image](https://user-images.githubusercontent.com/48471976/161280460-f9c8333e-d5c1-4686-8911-e6a00e765a31.png)

I thought the problem was due to the difficulty of the experience, however when I tried to do some simulations with different ground truth distributions I got the same result.

For example. a uniform distribution gave the following comparison matrix:

![image](https://user-images.githubusercontent.com/48471976/161280381-be9d503e-d33a-414e-880e-b170bc050255.png)

It is clear that the algorithm always shifts towards the same pairs for the sides (high and low quality). 

This is somehow normal since we have a quality variance from one side only of the quality scale for the sides. 

However, what I am trying to achieve is an optimal pair selection in order to take the minimum number of comparisons possible. And in this case, we will have a lot of unused comparisons (for example instead of 30 of the same comparisons (0,1) we can only do 10, etc). 

Do you think we can solve this?

Thank you very much!

Nicolas

**Comment by mikhailiuk** [comment]
Hi @nicolasch96,

Thanks a lot for your question again! 

It is a very valid concern that you have. I have done exactly the same experiment while working on the method and wasn't sure if this comparison distribution is optimal. In addition to the number of comparisons I have also checked the information gain matrix (similar plot) and change in the scores from each iteration and it appears that the comparison concentration at either end of the scale is justified by the added information from each subsequent comparison. 

One of the ways to fix it (although quite hardcoded) is weighting the information gain from each comparison by the number of comparisons performed so far between two conditions. 

If you decide to try that one or come up with anything else do let me know!

P.s. really enjoy your questions as they always come with some work done :)

Thanks,

Aliaksei
