### ISSUE TITLE
Benchmark code

### ISSUE THREAD

**Issue by pencilzhang** [gfxdisp/asap#5]
Hello,
Thanks for your great work!
You already include swiss system and ard methods for comparison.
I am wondering if you will release the code to implement other methods in the near future？

Thanks!
Jun

**Comment by mikhailiuk** [comment]
Hi Jun,

Thanks for the question. 

I will be pushing more code in the coming weeks. 

In the mean time you might as well check out the original repositories of the methods used in the paper, some of them contain benchmark methods as well. For example Hybrid-MST has its own implementation of several methods which we compare against in our work: https://github.com/jingnantes/hybrid-mst

Please let me know if there is anything else I could help you with.

Best,

Aliaksei

**Comment by pencilzhang** [comment]
> Hi Jun,
> 
> Thanks for the question.
> 
> I will be pushing more code in the coming weeks.
> 
> In the mean time you might as well check out the original repositories of the methods used in the paper, some of them contain benchmark methods as well. For example Hybrid-MST has its own implementation of several methods which we compare against in our work: https://github.com/jingnantes/hybrid-mst
> 
> Please let me know if there is anything else I could help you with.
> 
> Best,
> 
> Aliaksei

Hello Aliaksei,

Thanks for your information. I should explore more.

Glad to hear that you will push more things. Really nice work!

Best,
Jun
