### ISSUE TITLE
ASAP matlab code error

### ISSUE THREAD

**Issue by pencilzhang** [gfxdisp/asap#6]
Hi, when I tried to run matlab code, there is an error about matrix dimensions, see below.

Any idea about that?  Thanks!

Error using  - 
Matrix dimensions must agree.

Error in ts_solve (line 38)
  Psg = reshape(Ps(G),size(G)) - Pgs;

Error in compute_information_gain_mat (line 7)
    [out_data]=ts_solve(init_data);

Error in run_asap (line 24)
    [inf_mat,init_data,pairs_to_compare]=compute_information_gain_mat(N,init_data);

Error in example_running (line 9)
[pairs_to_compare, Mean, Std] = run_asap(M, 'mst');

**Comment by mikhailiuk** [comment]
Hi Jun,

Thanks for the question. 

I guess the reason might be in the version of Matlab you are running. 

The code was written on MATLAB_R2020a.

Let me know if there is anything else I could help you with.

Thanks,

Aliaksei

**Comment by pencilzhang** [comment]
> Hi Jun,
> 
> Thanks for the question.
> 
> I guess the reason might be in the version of Matlab you are running.
> 
> The code was written on MATLAB_R2020a.
> 
> Let me know if there is anything else I could help you with.
> 
> Thanks,
> 
> Aliaksei

Hello Aliaksei,

Thanks for your response. Indeed, I am using matlab_r2014b which is probably too old:)
I will try with the r2020a. Thanks for your suggestion.

Best,
Jun
