### ISSUE TITLE
Extract Ranking

### ISSUE THREAD

**Issue by SasCezar** [gfxdisp/asap#7]
Hi,

I'm trying to understand if it is possible to get metrics from the code that let me know if it converged, and also how to obtain the ranked list of the items.

If not, do you have any suggestions on a good way to extract the ranking?

Thanks!

**Comment by mikhailiuk** [comment]
Hi,

Thanks for raising the issue!

I will add code to extract ranking by the end of the day. This will consist of the score and the standard deviation of the score.

I will let you know once done.

As for convergence - you could monitor both the change in the scores and the standard deviation - setting a threshold on the required confidence.

Thanks again,

Aliaksei

**Comment by mikhailiuk** [comment]
Hi @SasCezar,

It's there! 

Thanks again for raising the issue
